config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get 'sign_up' => "users#new"
  resources :users, only: [:create, :index] do
    member do
      post :friend_request
      post :accept_request

      delete :decline_request
    end
  end

  get 'log_in' => "sessions#new"
  post 'log_in' => "sessions#create"
  delete 'log_out' => "sessions#destroy"

  resources :posts, shallow: true do 
    resources :comments, except: [:index, :show, :new]
  end

  resources :profiles, only: [:show, :edit, :update]
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <%= javascript_tag "Materialize.toast('#{msg}', 4000, '#{key}')" %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="nav-extended">
   <div class="nav-wrapper">
    <%= link_to "Authentication ", root_path, class: "brand-logo" %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Find friends", users_path %></li>
      <% if logged_in? %>
        <li><%=link_to current_user.full_name, current_user.profile %></li>
        <li><%= link_to "Log Out", log_out_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Log In", log_in_path %></li>
        <li><%= link_to "Sign Up", sign_up_path %></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Find friends", users_path %></li>
      <% if logged_in? %>
        <li><%=link_to current_user.full_name, current_user.profile %></li>
        <li><%= link_to "Log Out", log_out_path, method: "delete" %></li>
      <% else %> 
        <li><%= link_to "Log In", log_in_path %></li>
        <li><%= link_to "Sign Up", sign_up_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/flash' %>
    <main>
      <%= yield %>
    </main>
    <div class="spinner"><%= render "shared/spinner", size: "small" %></div>
  </body>
</html>